# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CardList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Kingfisher'
pod 'lottie-ios'
pod 'Firebase/Database'
  # Pods for CardList

end
